vim.opt.wrap = true
vim.opt.linebreak = true
vim.opt.breakat = " ^I!@*-+;:,./?"
vim.opt.breakindent = true
vim.opt.foldlevel = 99
vim.opt.foldmethod = "expr"
vim.opt.foldcolumn = "1"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.opt.number = false
vim.opt.relativenumber = false
vim.opt.conceallevel = 3
vim.opt.concealcursor = "nc"
vim.opt.spelllang = "en_us"
vim.opt.spell = true
